INIT_POPULATION_PATH = 'resources/raw/carreaux_200m_met_2019.csv'
INIT_GRT_PATH = 'resources/raw/trace-du-reseau-grt-250.csv'
INIT_TEREGA_PATH = 'resources/raw/terega-trace-du-reseau.csv'
POPULATION_PATH = 'resources/pop_filtered.csv'
GAZ_NETWORK_PATH = 'resources/gaz_network.csv'
GAZ_NETWORK_COLORED_PATH = 'resources/gaz_network_colored.csv'
